Fix: update readme
nhrap-dev/FHIT pull request #9
Opened 2021-12-01 20:18 UTC by clindeman

Replace all anaconda references with miniforge. Change hand drawn red circles with straight red lines in screenshots.

2021-12-02 14:57 UTC, be-cunning requested changes
Just needs a few sentence corrections - to use active tone.

Also, these commits are a 'chore', instead of a 'fix'.

2021-12-02 14:57 UTC, be-cunning commented on README.md
> +The Flood Hazard Import Tool requires Hazus, Conda, and an internet connection. If you haven't already, follow this [README](https://github.com/nhrap-dev/Environment-Setup/tree/update-README) to setu
Use an active tone. Change the second sentence to:

Follow the [README](https://github.com/nhrap-dev/Environment-Setup/tree/update-README) to setup your machine with miniforge and conda before running FHIT.

2021-12-02 14:57 UTC, be-cunning commented on README.md
> +1. Download zip folder of tool from GitHub, unzip.
Change to this for clarity:

_Download zip folder of tool from GitHub, then unzip._

2021-12-03 01:00 UTC, clindeman commented on README.md
> +The Flood Hazard Import Tool requires Hazus, Conda, and an internet connection. If you haven't already, follow this [README](https://github.com/nhrap-dev/Environment-Setup/tree/update-README) to setu
Applied recommended active tone.

2021-12-03 01:00 UTC, clindeman commented on README.md
> +1. Download zip folder of tool from GitHub, unzip.
Applied recommendation for clarity.

2021-12-03 18:19 UTC, merged